version: "3.0"
volumes:
  msdata:
  mslogs:
  mssecr:

services:    
  scanners_init:
      image: busybox:latest
      command: sh -c "chown -R 3003:0 /home/rocket/.jenkins/workspace && chown -R 3003:0 /home/rocket/tomcat/logs"
      volumes:
      - ./di_scanners_tomcat_logs:/home/rocket/tomcat/logs
      - ./di_scanners_workspace:/home/rocket/.jenkins/workspace

  di-scanners:
    image: ${DI_SCANNERS}
    container_name: di-scanners
    hostname: di-scanners
    #command: sh -c "sleep 9999999"
    ports:
      - '${DI_SCANNERS_EXTERNAL_PORT}:8080'
    extra_hosts:
      - "mssql2017:${DI_LOCAL_IP}"
      - "di-server:${DI_LOCAL_IP}"
    volumes:
    - ./di_scanners_workspace:/home/rocket/.jenkins/workspace
    - ./di_scanners_tomcat_logs:/home/rocket/tomcat/logs
    depends_on:
      - scanners_init
  
  mssql2017:
    image: 'mcr.microsoft.com/mssql/server:2017-latest'
    container_name: mssql2017
    hostname: mssql2017
    ports:
      - '1433:1433'    
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Rocket2023"
    volumes:
    - msdata:/var/opt/mssql/data
    - mslogs:/var/opt/mssql/log
    - mssecr:/var/opt/mssql/secrets
    - ./samples:/samples
