version: "3.0"
      
volumes:
  di_solr_data:
  di-indexupd_logs:
  di-indexupd_conf:
  di_server_datbas:
  di_server_appl:
  di_workflow_dbdata:
  di_webapp_conf:
  di_webapp_logs:
  
  




services:   
  db1_empty_init:
      image: guillermoavendano/di-db1empty:10.00.002
      command: sh -c "if [ ! -e /home/rocket/rochade/datbas/d1.rodb ]; then cp /root/d1.rodb /home/rocket/rochade/datbas/d1.rodb; fi"
      volumes:
      - di_server_datbas:/home/rocket/rochade/datbas

  db2_empty_init:
      image: guillermoavendano/di-db2empty:10.00.002
      command: sh -c "if [ ! -e /home/rocket/rochade/datbas/d2.rodb ]; then cp /root/d2.rodb /home/rocket/rochade/datbas/d2.rodb; fi"
      volumes:
      - di_server_datbas:/home/rocket/rochade/datbas

  datainit:
      image: busybox:latest
      command: sh -c "chown -R 3003:0 /home/rocket/rochade/appl && chown -R 3003:0 /home/rocket/rochade/datbas && chown -R 3003:0 /home/rocket/Index_Update_Service/conf && chown -R 3003:0 /home/rocket/Index_Update_Service/logs && chown -R 3003:0 /home/rocket/conf && chown -R 3003:0 /home/rocket/tomcat/logs"
      volumes:
      - di_server_appl:/home/rocket/rochade/appl
      - di_server_datbas:/home/rocket/rochade/datbas
      - di-indexupd_conf:/home/rocket/Index_Update_Service/conf
      - di-indexupd_logs:/home/rocket/Index_Update_Service/logs
      - di_webapp_conf:/home/rocket/conf
      - di_webapp_logs:/home/rocket/tomcat/logs
      depends_on:
      - db1_empty_init
      - db2_empty_init
  di-workflow:
    image: postgres:14-alpine
    container_name: di-workflow
    hostname: di-workflow
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: ${DI_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${DI_POSTGRES_PASS:-postgres}
    volumes:
      - di_workflow_dbdata:/var/lib/postgresql/data"
      - ./create_workflow_db.sh:/docker-entrypoint-initdb.d/create_workflow_db.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  di-server:
    image: 'guillermoavendano/di-server:10.00.002'
    container_name: di-server
    hostname: di-server
    #command: sh -c "sleep 9999999"
    environment:
      DI_SERVER_LICENSE_NUMBER: ${DI_SERVER_LICENSE_NUMBER}
      DI_SERVER_LICENSE_COMPANY: ${DI_SERVER_LICENSE_COMPANY}
    ports:
      - '8888:8888'
    volumes:
    - di_server_datbas:/home/rocket/rochade/datbas
    - di_server_appl:/home/rocket/rochade/appl
    depends_on:
      - datainit      
      - db1_empty_init
      - db2_empty_init

  di-solr:
    image: guillermoavendano/di-solr:8.11.2
    container_name: di-solr
    hostname: di-solr
    ports:
     - "8983:8983"
    volumes:
      - di_solr_data:/var/solr
  di-indexupd:
    image: 'guillermoavendano/di-indexupd:10.00.002'
    container_name: di-indexupd
    command: sh -c "sleep 9999999"
    environment:
       DI_SOLR_HOST: ${DI_SOLR_HOST}
       DI_SOLR_PORT: 8983
       DI_SERVER_HOST: ${DI_SERVER_HOST}
       DI_SERVER_PORT: 8888
       DI_SERVER_USER: ${DI_SERVER_USER}
       DI_SERVER_PASS: ${DI_SERVER_PASS}
    volumes:
    - di-indexupd_conf:/home/rocket/Index_Update_Service/conf
    - di-indexupd_logs:/home/rocket/Index_Update_Service/logs
    depends_on:
      - datainit
      - di-solr  

  di-webapp:
    image: 'guillermoavendano/di-webapp:10.00.002'
    container_name: di-webapp
    hostname: di-webapp
    #command: sh -c "sleep 9999999"
    ports:
      - 8080:8080
    environment:
       DI_SOLR_HOST: ${DI_SOLR_HOST}
       DI_SOLR_PORT: 8983
       DI_SERVER_HOST: ${DI_SERVER_HOST}
       DI_SERVER_PORT: 8888
       DI_SERVER_USER: ${DI_SERVER_USER}
       DI_SERVER_PASS: ${DI_SERVER_PASS}
       DI_POSTGRES_HOST: ${DI_POSTGRES_HOST}
       DI_POSTGRES_PORT: 5432
       DI_POSTGRES_USER: ${DI_POSTGRES_USER}
       DI_POSTGRES_PASS: ${DI_POSTGRES_PASS}
       DI_WEBAPP_HOST: ${DI_WEBAPP_HOST}
    volumes:
    - di_webapp_conf:/home/rocket/conf
    - di_webapp_logs:/home/rocket/tomcat/logs
    depends_on:
      - datainit  
      - di-server