version: "3.0"
      
volumes:
  di_solr_data:
  
services:   
  db1_empty_init:
      image: ${DI_DB1_IMAGE}
      command: sh -c "if [ ! -e /home/rocket/rochade/datbas/d1.rodb ]; then cp /root/d1.rodb /home/rocket/rochade/datbas/d1.rodb ; cp /root/d1.md5 /home/rocket/rochade/datbas/d1.md5 ; fi"
      volumes:
      - ./di_server_datbas:/home/rocket/rochade/datbas

  db2_empty_init:
      image: ${DI_DB2_IMAGE}
      command: sh -c "if [ ! -e /home/rocket/rochade/datbas/d2.rodb ]; then cp /root/d2.rodb /home/rocket/rochade/datbas/d2.rodb ; cp /root/d2.md5 /home/rocket/rochade/datbas/d2.md5 ; fi"
      volumes:
      - ./di_server_datbas:/home/rocket/rochade/datbas

  data_init:
      image: busybox:latest
      command: sh -c "chown -R 3003:0 /home/rocket/rochade/appl && chown -R 3003:0 /home/rocket/rochade/datbas && chown -R 3003:0 /home/rocket/Index_Update_Service/conf && chown -R 3003:0 /home/rocket/Index_Update_Service/logs && chown -R 3003:0 /home/rocket/conf && chown -R 3003:0 /home/rocket/tomcat/logs && chown 8983:8983 -R /var/solr/data/configsets"
      volumes:
      - ./di_server_appl:/home/rocket/rochade/appl
      - ./di_server_datbas:/home/rocket/rochade/datbas
      - ./di_indexupd_conf:/home/rocket/Index_Update_Service/conf
      - ./di_indexupd_logs:/home/rocket/Index_Update_Service/logs
      - ./di_webapp_conf:/home/rocket/conf
      - ./di_webapp_logs:/home/rocket/tomcat/logs
      - di_solr_data:/var/solr
      depends_on:
      - db1_empty_init
      - db2_empty_init
