# Author: Guilllermo Avendaño
# Creation Date: 11/27/2023
# Fix user owner for copied directories, and files 02/08/2024
FROM solr:8.11.2


ENV DI_SOLR_CONFIG_DIR=/var/solr/data/configsets

USER 8983

RUN mkdir $DI_SOLR_CONFIG_DIR

COPY --chown=8983:8983 ./rochade          $DI_SOLR_CONFIG_DIR/rochade/   

COPY --chown=8983:8983 ./configsets/BigData_configs          $DI_SOLR_CONFIG_DIR/BigData_configs/        
COPY --chown=8983:8983 ./configsets/DataIntegration_configs  $DI_SOLR_CONFIG_DIR/DataIntegration_configs/
COPY --chown=8983:8983 ./configsets/Models_configs           $DI_SOLR_CONFIG_DIR/Models_configs/       
COPY --chown=8983:8983 ./configsets/Stitching_configs        $DI_SOLR_CONFIG_DIR/Stitching_configs/  
COPY --chown=8983:8983 ./configsets/BusinessIntelligence_configs  $DI_SOLR_CONFIG_DIR/BusinessIntelligence_configs/ 
COPY --chown=8983:8983 ./configsets/DataQualityManagement_configs $DI_SOLR_CONFIG_DIR/DataQualityManagement_configs/  
COPY --chown=8983:8983 ./configsets/DWRView_configs          $DI_SOLR_CONFIG_DIR/DWRView_configs/  
COPY --chown=8983:8983 ./configsets/ReferenceData_configs    $DI_SOLR_CONFIG_DIR/ReferenceData_configs/  
COPY --chown=8983:8983 ./configsets/BusinessTermView_configs $DI_SOLR_CONFIG_DIR/BusinessTermView_configs/  
COPY --chown=8983:8983 ./configsets/DataStructure_configs    $DI_SOLR_CONFIG_DIR/DataStructure_configs/  
COPY --chown=8983:8983 ./configsets/metaApp_configs          $DI_SOLR_CONFIG_DIR/metaApp_configs/
