# Author: Guilllermo Avendaño
# Cretion Date: 11/27/2023
FROM solr:8.11.2

ENV DI_SOLR_CONFIG_DIR=/var/solr/data/configsets

COPY ./configsets/BigData_configs          $DI_SOLR_CONFIG_DIR/BigData_configs/        
COPY ./configsets/DataIntegration_configs  $DI_SOLR_CONFIG_DIR/DataIntegration_configs/
COPY ./configsets/Models_configs           $DI_SOLR_CONFIG_DIR/Models_configs/       
COPY ./configsets/Stitching_configs        $DI_SOLR_CONFIG_DIR/Stitching_configs/  
COPY ./configsets/BusinessIntelligence_configs  $DI_SOLR_CONFIG_DIR/BusinessIntelligence_configs/ 
COPY ./configsets/DataQualityManagement_configs $DI_SOLR_CONFIG_DIR/DataQualityManagement_configs/  
COPY ./configsets/DWRView_configs          $DI_SOLR_CONFIG_DIR/DWRView_configs/  
COPY ./configsets/ReferenceData_configs    $DI_SOLR_CONFIG_DIR/ReferenceData_configs/  
COPY ./configsets/BusinessTermView_configs $DI_SOLR_CONFIG_DIR/BusinessTermView_configs/  
COPY ./configsets/DataStructure_configs    $DI_SOLR_CONFIG_DIR/DataStructure_configs/  
COPY ./configsets/metaApp_configs          $DI_SOLR_CONFIG_DIR/metaApp_configs/

