version: '3'
services:
  mailserver:
    image: analogic/poste.io
    container_name: mailserver-sysbeards
    restart: always
    #network_mode: "host"
    ports:
      - "6060:8080"
      - "4443:4443"
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    environment:
      - h=mail.rocketsoftware.com
      - HTTP_PORT=6060
      - HTTPS_PORT=4443
      - DISABLE_CLAMAV=TRUE
    volumes:
      - ./data:/data
