apiVersion: v1
kind: Service
metadata:
  name: mailserver  
  namespace: mobius
  annotations:
    service.kubernetes.io/topology-mode: auto
spec:
  ports:
    - port: 25
      name: smtp
      protocol: TCP
      targetPort: 25
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: mailserver-es
  namespace: mobius
  labels:
    kubernetes.io/service-name: mailserver
addressType: IPv4
ports:
  - name: smtp
    protocol: TCP
    port: 25
endpoints:
  - addresses:
      - "172.23.112.204"
    conditions:
      ready: true